version: "3.6"

services:

  self-hosted-sso-server:
    image: soulteary/sso-server:1.1.2
    container_name: sso-server
    hostname: sso-server
    restart: always
    expose:
      - 80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: ./main
    extra_hosts:
      - "$SERVER_DOMAIN:0.0.0.0"
    networks:
      - traefik
    environment:
      - TZ=Asia/Shanghai
      - PORT=${SERVER_LISTEN_PORT:-80}
      - SESSION_SECRET=${SESSION_SECRET:-}
      - SERVER_NAME=${SERVER_NAME:-}
      - CLIENT_NAME=${CLIENT_NAME:-}
      - CLIENT_ID=${CLIENT_ID:-}
      - CLIENT_SECRET=${CLIENT_SECRET:-}
      - CLIENT_ISTRUSTED=${CLIENT_ISTRUSTED:-}
      - USER_PASS=${USER_PASS:-}
      - LICENSE=${LICENSE:-}
      - LICENSE_FILE=${LICENSE_FILE:-}
      - OTP_OPTION=${OTP_OPTION:-}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      - "traefik.http.routers.sso-web.entrypoints=http"
      - "traefik.http.routers.sso-web.rule=Host(`$SERVER_DOMAIN`)"

      - "traefik.http.routers.sso-ssl.entrypoints=https"
      - "traefik.http.routers.sso-ssl.tls=true"
      - "traefik.http.routers.sso-ssl.rule=Host(`$SERVER_DOMAIN`)"

      - "traefik.http.services.sso-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.sso-backend.loadbalancer.server.port=80"
    logging:
        driver: "json-file"
        options:
            max-size: "10m"

networks:
  traefik:
    external: true


